from io import open

WIN_WIDTH=1312
WIN_HEIGHT=736
TILESIZE =32
FPS=15

WHITE=(255,255,255)
BLACK=(0,0,0)

PLAYER_LAYER=3
BLOCK_LAYER=2
WATTER_LAYER=2
GROUND_LAYER=1

PLAYER_SPEED=32
PLAYER_HEALTH=10
DAMAGE_COLLIDE=1
DAMAGE_WATTER=3
GENERAL_FONT="assests/fonts/arial_narrow_7.ttf"

BAR_HEIGHT = 20
HEALTH_BAR_WIDTH = 200
ITEM_BOX_SIZE=80
UI_FONT_SIZE=18

UI_BG_COLOR='#222222'
UI_BORDER_COLOR='#111111'
TEXT_COLOR='#EEEEEE'

HEALTH_COLOR='red'
UI_BORDER_COLOR_ACTIVE='gold'

with open('assests/maps/map1.txt', 'r') as file:
    first_tilemap = [list(line.strip()) for line in file]
